### ISSUE TITLE
Portfolio Section 내용 개선

### ISSUE THREAD

**Issue by item4** [Snoin/snoin.com#10]
지금 demo 사이트꺼 그대로 달려 있습니다.

뭐 뭐 넣어야 할까요?

일단 Snoin File Storage까진 알겠는데 나머지가 좀... 최소 3개는 있어야 하지 않나 싶어요

**Comment by sjkoon** [comment]
딱히 포트폴리오가 없어서 문제인데.. 제가 만들었던 웹사이트라도 넣어야 되나여..

**Comment by item4** [comment]
@Snoin/owners 결정을 해야할 것 같습니다. 파일창고만 넣기엔 너무 빈약하고, 그렇다고 제 블로그 같은걸 넣긴 웃기고.. 나머지 Xnova는 그렇다 해도 아쿠아런처는 넣기 좀 많이 웃기지 않나요?

**Comment by marnitto** [comment]
웹 에이전시 개념이면 아쿠아런처는 빼는 게 맞죠.
2015. 11. 11. 오후 11:29에 "item4" <notifications@github.com>님이 작성:

**Comment by LoveHoly** [comment]
그런 일아  있었는데 그것을 경력으로 쓴다는건 아무래도 우리팀의 오점입니다

**Comment by item4** [comment]
Xnova도 아쿠아런처도 끝이 좋지 않았는데 둘 다 넣지 말까요?

그러면 포트폴리오가 하나밖에 안남습니다만..

**Comment by marnitto** [comment]
끝이 좋은 케이스는 잘 없죠. 다만 아쿠아런처는 웹 개발과는 거리가 머니까 추가하지 앟는 게 좋아보입니다. Xnova는 제가 보기엔 성과 면에선 좋아보이는데 직접 결정하셔도 될 것 같아요.

**Comment by sjkoon** [comment]
포트폴리오 세션을 빼는건 어때요

**Comment by item4** [comment]
@sjkoon 포트폴리오가 없는 웹 에이전시도 있는가 싶긴 한데.. 어차피 지금 포트폴리오 두개 다 접속 불가능하군요..

@Snoin/owners 좀 과격한 방법인 것 같기도 한데, 포트폴리오를 아예 빼는 안건에 대한 의견 주세요.

**Comment by item4** [comment]
@Snoin/owners KST 11/15 23:00까지 아무 의견 없으면 포트폴리오 제거 PR 올라갑니다.

**Comment by marnitto** [comment]
정 낼 게 없으면 찬성합니다. 개인적으로는 파일창고와 Xnova는 정말 아쉬운데, 이건 @item4님 결정에 따르겠습니다.

**Comment by sjkoon** [comment]
아니면 파일창고와 xnova를 간단하게 양사이드에 배치해서 포트폴리오를 그냥 대충 가볍게 스크롤로 넘어갈 수 있는 정도로 하는건 어떨까요. (눈에 확 안띄게)

**Comment by EcmaXp** [comment]
@item4 KST 11/15 23:00 경과, 포트폴리오 제거 PR 필요.
