### ISSUE TITLE
Snoin 로고 확정

### ISSUE THREAD

**Issue by item4** [Snoin/snoin.com#102]
#100 이슈를 해결하려면 이미지 자리에 넣을 로고가 필요합니다.

**Comment by sjkoon** [comment]
![43logo](https://cloud.githubusercontent.com/assets/2350598/13194936/077ae034-d7e6-11e5-8f71-eba7042e8280.png)
![logo-charlie-text-logo](https://cloud.githubusercontent.com/assets/2350598/13194937/077e314e-d7e6-11e5-8c3b-4256cda6439f.png)

**Comment by item4** [comment]
@sjkoon 엠블럼 only 버전이 누락됬어요

**Comment by sjkoon** [comment]
![test](https://cloud.githubusercontent.com/assets/2350598/13196008/aff604b8-d805-11e5-90e9-a04c9efba5bb.png)
