### ISSUE TITLE
페이지 로딩 속도 최적화

### ISSUE THREAD

**Issue by EcmaXp** [Snoin/snoin.com#108]
https://developers.google.com/speed/pagespeed/insights/?url=snoin.com

- [압축 사용](https://developers.google.com/speed/docs/insights/EnableCompression)
- [스크롤 없이 볼 수 있는 콘텐츠에서 렌더링 차단 자바스크립트 및 CSS 삭제](https://developers.google.com/speed/docs/insights/OptimizeCSSDelivery)
- [이미지 최적화](https://developers.google.com/speed/docs/insights/OptimizeImages)
- [자바스크립트 축소](https://developers.google.com/speed/docs/insights/MinifyResources)
- [브라우저 캐싱 활용](https://developers.google.com/speed/docs/insights/LeverageBrowserCaching)

해당 사항 전부 적용시 1363 KB를 절약 할 수 있습니다.

**Comment by EcmaXp** [comment]
@sjkoon 
nginx에서 특별히 문제 없다면 [nginx gzip module](http://nginx.org/en/docs/http/ngx_http_gzip_module.html) 활성화 해주셨으면 합니다.

**Comment by item4** [comment]
[AMP](https://www.ampproject.org/)라는 솔루션도 있습니다. 이걸 도입하면 구글 검색어 순위에서 위로 올라간다고..

**Comment by EcmaXp** [comment]
gzip 미사용으로 패스.

**Comment by EcmaXp** [comment]
이미 충분히 최적화 되었다고 판단하여 닫습니다. (HTTP/2 적용)
