### ISSUE TITLE
About Section 내용 완성

### ISSUE THREAD

**Issue by item4** [Snoin/snoin.com#11]
연표의 연도와 날짜를 몰라서 완성을 못했습니다.

이미지도 필요하구요.

필요한 자료
---------------
* [x] Kkaul 시작 시점: 2006년
* [ ] Kkaul 시절 이미지
* [x] Snoin 개명 시점: 2007년 8월
* [ ] Snoin 상징 이미지
* [x] 파일창고 개시 시점: 2008년
* [ ] 파일창고 이미지
* [ ] 웹 서비스 제작 시작에 해당하는 이미지

**Comment by sjkoon** [comment]
kkaul 시작시점의 이미지를 제가 찾아볼게요. 설명은 뭐 제가 대충 써보죠
완성후 추가 코멘트로 적어두겠습니다.

Snoin 개명시점은 2007년입니다.
상징이미지는 뭐 로고나 넣어둬야..

창고개시 는 2008년이며 이미지는 뭐... 저번에 드렸던 그 스샷 .

웹서비스 제작  시작은 이미지 할게 있나요..... 삽 아이콘이라도 넣어야되나.. 의견주세여.

**Comment by marnitto** [comment]
웹 서비스 시작 쪽은 @sjkoon 이 말씀하셨던 대로 그냥 적당히 희망찬(?) 식으로 쓰는 게 낫지 않을지...

**Comment by sjkoon** [comment]
kkaul.com 시작시점의 이미지가 심각히 저화질이라 문제네요.

snoin 개명시점은 2007년 8월으로 제 다이어리에 적혀있고요..

웹서비스 시작 쪽은 뭔가 도전적인 느낌으로 적어야 할거같은데. 일단 틀 잡기위해 커멘트 해놓습니다.

**Comment by item4** [comment]
@sjkoon 내용 아직인가요

**Comment by item4** [comment]
@sjkoon 확인 요망
