### ISSUE TITLE
CSS/SCSS 문법 표준 결정

### ISSUE THREAD

**Issue by item4** [Snoin/snoin.com#113]
CSS/SCSS를 아울러서 쓸 수 있는 것이 없어서 방치상태였는데, 마침 잘 정리된 물건이 홍보되고 있어서 실험해본 결과 나쁘지 않다고 생각해서 제안합니다.

문법명: [stylelint-config-standard](https://github.com/stylelint/stylelint-config-standard)

The Idiomatic CSS Principles, Github's PrimerCSS Guidelines, Google's CSS Style Guide, Airbnb's Styleguide, @mdo's Code Guide 등의 물건에서 적당히 추린 물건이라고 합니다.

이 문법을 준수했는지의 검사는 [stylelint](https://github.com/stylelint/stylelint)를 사용해서 검사하고자 합니다.

## 장점

1. 널리 쓰이는 컨벤션의 총집편이므로 사용성 및 결과물의 가독성, 재사용성 등의 측면에서 기대할 만 하다
2. 같이 사용을 제안하려고 하는 stylelint와 짝을 이룬다

## 단점

1. 컨벤션 검사 규칙으로써는 존재하지만 구체적인 사용법이 문서로 없어서 실제로 문제가 발생해서 linter에 걸리기 전까진 알 수가 없다. 분석이 그리 크게 어려울 것 같지는 않지만 분석이 완료될 때 까지 문서를 통한 학습을 할 수가 없다.

**Comment by marnitto** [comment]
단점 부분에서 수동 처리해야 한다는 게 무슨 말씀이신지 잘 모르겠네요. IDE 단에서 autocomplete처럼 lint check가
불가능하다는 말씀이신가요? 기존에 커밋 훅이나 로컬 테스트처럼 처리하는 방식이라면, 크게 방법적으로 달라지는 건 없으니 편하신 대로
처리해도 될 것 같습니다.

**Comment by item4** [comment]
@marnitto 말 그대로 Rule에 대한 documentation이 하나도 없어서 합의용으로 쓰기가 애매합니다

**Comment by marnitto** [comment]
linter를 디버깅하는 상황이 되는 건 그다지 좋은 생각이 아닌 것 같네요... :(

제 생각엔 @item4 님께서 작성하신 코드의 기본 규칙을 토대로 진행하셔도 괜찮습니다. 나중에 documentation이나
linter check 문제가 어느 정도 해소되면 그때 고려하고요.

**Comment by item4** [comment]
@marnitto 디버깅.. 까진 필요 없고, 그냥 좀 뜯어보면 됩니다. 다행히 각각의 minimal한 규칙들은 공식문서가 있어서요

**Comment by item4** [comment]
https://item4.github.io/2016-04-25/stylelint-config-standard/

@Snoin/owners stylelint-config-standard에서 명시하는 표준입니다.
문서 분량은 참혹할 정도로 길지만 사실 별거 없습니다. (...)
우리는 저기에 몇가지 규칙만 추가해서 쓰면 되지 않을까 싶은데요

**Comment by marnitto** [comment]
찬성합니다. 제가 SCSS를 쓸 일이 없을지 모르겠지만...

**Comment by item4** [comment]
우리가 지키고 있는 룰 중 누락된 것이 있어서 추가하자면 `declaration-block-properties-order`을 `"alphabetical"`로 주었으면 합니다.

속성명을 알파벳순으로 정렬해서 `border`가 `color` 보다 먼저 와야하는 강제입니다.

**Comment by sjkoon** [comment]
stylelint-config-standard 사용 괜찮을듯하네요


공부를 또 해야하는건 함정이지만

**Comment by EcmaXp** [comment]
표준 HTML5을 준수하는 CSS에서 저 stylelint를 통과할 경우에 예제로서 제공하는 건 어떤가요.

**Comment by marnitto** [comment]
@EcmaXp 표준 html5을 준수하면서, 제안하는 stylelint를 통과하는 css 예제를 보여주는 게 어떻겠냐는 말씀이시죠?

**Comment by item4** [comment]
@marnitto @EcmaXp https://github.com/item4/item4.github.io/commit/709f796764058e0da4a3aadf4930071abd612d25

제 블로그에 이미 적용해놓은 commit diff입니다. 예시가 필요하다면 diff가 전후비교가 되서 좋을 것 같다고 생각합니다.

**Comment by EcmaXp** [comment]
@marnitto 네 <del>(HTML5를 지원하는 CSS라니 ㅈㅅ)</del>

**Comment by item4** [comment]
이론 없다면 빠른 시일 내에 #112 와 함께 PR 올리겠습니다.

**Comment by item4** [comment]
처리 완료됨
