### ISSUE TITLE
Contact Us 동작하게

### ISSUE THREAD

**Issue by item4** [Snoin/snoin.com#13]
제 생각엔 팀원 전원에게 **메일을 발송하는 방식**이 좋지 않을까 생각했습니다.

안그러면 또 DB Model을 깎는 나날이 시작될 것 같기도 하고, 관리자 페이지도 만들어야 하니까요.

**Comment by item4** [comment]
사실상 #4 랑 같은 이슈가 되었네요

**Comment by sjkoon** [comment]
메일발송으로 가는게 제일 구독하기도 쉬울듯..

**Comment by item4** [comment]
@sjkoon 이참에 Snoin 회원 전체용 메일링 리스트를 만들거나 하는건 어떨까요?

**Comment by marnitto** [comment]
메일링 리스트 방식도 생각해볼 수 있는데, 혹시나 싶어서 구글 업무용 메일을 살펴보니 사용자당 월 5달러부터 시작하네요. 기존에 snoin.com 도메인으로 메일 도메인 세팅하시던 거 있나요?

**Comment by item4** [comment]
1. 메일링 리스트를 만든다
2. 작업 전용 메일 계정을 만든다
3. 그냥 메일주소 모아서 메일링한다

**Comment by sjkoon** [comment]
snoin.com 도메인 메일은 현재 살아 있읍니다. 저만 사용하고 있지만...

구글앱스입니다.

**Comment by item4** [comment]
@sjkoon 그럼 2번으로 진행하는건가요. 계정 발급이 필요하니까 IRC에서 이야기하면 좋을 것 같네요

**Comment by sjkoon** [comment]
이부분 Close인가요?

**Comment by item4** [comment]
@sjkoon 아직 API만 제작되었고 프론트단이 안되었습니다. 프론트단 머지되면 자동으로 close 되게 하겠습니다.

**Comment by item4** [comment]
@Snoin/owners 현재 문제가 3가지 있습니다.

1. 현재 프론트엔드 필요 빌드 등등을 gulp로 하고 있습니다. 근데 아무래도 얘로 뭘 하는건 한계가 온 것 같습니다. 뭘 더 추가할 수가 없습니다. -_-; 파일 늘리면 JS 에러나요.
2. 그 여파는 아닌 것 같지만 `fetch` API가 testing이 안되는 현상이 발생하고 있습니다.
3. snoin 서버쪽 API가 500을 냅니다. 간단히 말해서 **고장났어요**

1번의 해법은 webpack으로 갈아타는 것 말고는 안떠오릅니다.
2번은 -_- 최악의 경우 그냥 테스팅을 포기해야할지도 모르겠습니다.
3번은 원인 분석이 시급합니다.

**Comment by item4** [comment]
2번은 밤샘 공부&삽질 결과 고쳤습니다.

3번 분석 들어갑니다.

**Comment by EcmaXp** [comment]
#60
