### ISSUE TITLE
Font 정리

### ISSUE THREAD

**Issue by item4** [Snoin/snoin.com#15]
지금 제가 폰트를 임의로 바꿔놓긴 했는데, 좀 더 정리가 필요합니다.

**Comment by sjkoon** [comment]
폰트는 그냥 나눔고딕이나 구글에서 이번에 배포한 폰트가 나을거 같다는 생각이 드는군요

**Comment by item4** [comment]
@sjkoon 현재 본문은 나눔고딕으로 되어있을겁니다. 그런데 몇몇 부분이 폰트가 뒤섞여있어서 그 부분의 정리가 필요하단 의미였어요

**Comment by sjkoon** [comment]
폰트를 나눔고딕으로 통일 하는 거는 어떻게 생각하세요.

**Comment by item4** [comment]
@Snoin/owners 현재 잡탕으로 import되는 폰트를 좀 정리하고 스크린샷으로 비교를 해서 보여드리겠습니다.

**Comment by item4** [comment]
현재 쓰이는 폰트 중 영문 폰트는 2종류입니다. (안쓰는 웹폰트 제거 PR은 곧 올립니다.)

Montserrat
---------------
<img width="361" alt="2015-11-11 10 45 24" src="https://cloud.githubusercontent.com/assets/559952/11092404/79cd3c50-88c6-11e5-9a90-9c00eeb8b88b.png">
<img width="141" alt="2015-11-11 10 45 51" src="https://cloud.githubusercontent.com/assets/559952/11092403/79cce692-88c6-11e5-8ead-58bb21cd7a07.png">

타이틀 같은 부분에서 한글, 영어 두 곳 모두 쓰이고 있는데 한글 부분에서 secondary font가 **없는걸로** 확인되었습니다.

Roboto Slab
-----------------
<img width="346" alt="2015-11-11 10 46 19" src="https://cloud.githubusercontent.com/assets/559952/11092402/79ca3794-88c6-11e5-88cd-5004bfb2ab5c.png">

이쪽은 좀 더 심각합니다. 한글 빈도가 아예 더 높은데 한글 지원이 안됩니다.

제 의견
---------
1. Montserrat 뒤에 나눔고딕(또는 나눔바른고딕) 추가
2. Roboto Slab을 나눔고딕(또는 나눔바른고딕)으로 대체

@Snoin/owners 의견 주세요.

**Comment by marnitto** [comment]
Roboto Slab + 나눔바른고딕 추천합니다.

영문 폰트와 한글 폰트와의 조화를 중심으로 생각했고요, 나눔고딕은 좀 많이 끊기는 느낌이 있어서 개인적으로 나눔바른고딕을 좋아합니다.
2015. 11. 11. 오후 10:52에 "item4" <notifications@github.com>님이 작성:

**Comment by item4** [comment]
저도 나눔바른고딕 찬성인데, 따로 web font로 만들 필요성이 있습니다. google font earlyaccess에선 아직 제공 안하네요.

**Comment by item4** [comment]
만드는건 어려운 문제는 아니지만.. 제가 Roboto Slab를 빼고 싶었던 이유는 로딩 속도 저하.. 인데, 영문폰트니까 크게 상관 없을까요?

**Comment by marnitto** [comment]
목적에 따라 다르다고 봅니다.

메인 페이지처럼 포폴로 쓰는 거면 디자인이 졔일 중요하니 웹폰트를 쓰겠죠. 너무 느리다 싶으면 특정 폰트를 쓰는 곳(타이틀 등)만
이미지로 바꿔도 되고요.

나눔바른고딕 웹폰트 변환하면 저작권 문제는 없나요? 아예 본고딕으로 통일해도 괜찮아보이기도 하고요.

**Comment by sjkoon** [comment]
음 저도 로딩속도 저하가 있다면 그부분은 이미지로 가는게 맞다고 봐요. 그게 아니라면 단일 폰트로 통일하는것이 낫다고 봅니다.

**Comment by item4** [comment]
@sjkoon @marnitto 
1. 영문폰트는 생각보다 가볍습니다
2. 한글폰트는 생각보다 무겁습니다
3. 웹 접근성, 시멘틱을 운운하면서 컨텐츠를 이미지로 만들면 신뢰성에 금이 간다고 생각합니다.
4. 나눔바른고딕은 포맷 변경해도 될 것 같습니다. [(참고)](https://help.naver.com/support/contents/contents.nhn?serviceNo=1074&categoryNo=3497)
5. 본고딕, 그러니까 Noto Sans CJK는 한국어만 쓰지 않는 한 더 무겁습니다.
6. [이 문제를 해결한 웹폰트가 국내에 딱 1종류 있습니다.](http://www.spoqa-han-sans.com/) 이 폰트를 집어다 쓰거나, 이 폰트처럼 [작업을 하면](http://spoqa.github.io/2015/10/14/making-spoqa-han-sans.html) 되지 않을까 생각합니다.

**Comment by item4** [comment]
추가적으로, 지금 한글 폰트가 이미 2종류 투입되어 있습니다.

<img width="573" alt="2015-11-12 2 25 39" src="https://cloud.githubusercontent.com/assets/559952/11111153/465e4728-8949-11e5-9902-c535abba7a1f.png">

각각 나눔명조, 나눔 펜 필기체 입니다.

**Comment by marnitto** [comment]
폰트 작업 전에, "무겁다"와 "가볍다"를 어느 기준으로 사용하시는지, 그리고 이 작업에서 폰트를 바꾸는 데 어느 정도까지 고려해야 할까요? 현재 snoin.com 올라온 것을 기준으로 구글 웹 폰트 로딩하는 게 font- 
awesome을 제외하고 총 5개인데, 사이즈가 최대 1051KB이고 최대 로딩 시간이 333ms여서 이 정도면 메인 페이지가 그렇게까지 느리다고 무겁다고 생각하진 않거든요. 다른 것들은 아직 도입이 안 됐으니 모르겠고요.

사족으로,item4님께서 spoqa 기업에 대해 굉장히 긍정적으로 생각하시는 건 잘 알겠습니다만, 간혹 전해주시는 정보가 정말 팀 전체에 도움이 되어서 도입하시는 것인지 의아할 때가 있습니다. Spoqa와 저를 비교한 
다면 당연히 제가 역량도 지식도 부족한데, 그렇다고 거기 있는 모든 걸 다 따라하다간 아무 성과물도 안 나올 것 같거든요. 마지막에 작성하셨던 것은 결론적으로 폰트 경량화 작업까지 필요하다는 말씀이신지요?

**Comment by item4** [comment]
@marnitto 본고딕을 쓸거라면 이미 저기서 줄여놓은게 있다는 의미였고, 저기서 줄인 방법을 똑같이 쓰면 나눔폰트시리즈도 줄여서 쓸 수 있습니다. 다 따라하자는게 아니라 폰트 경량화에 대해서 최근에 언급된 블로그가 마침 저기였어요.

**Comment by item4** [comment]
그리고 로딩 속도는... 사실 PC+유선 환경에선 별로 티가 안나는 것 같습니다. 이미 사전에 PC에 폰트가 있으면 더더욱이 그렇구요. 모바일 환경에서의 느림이 문제인 것 같습니다.

**Comment by marnitto** [comment]
모바일은 데이터 때문에 웹폰트를 사용하지 않는 게 제일 좋아보입니다... ㅠㅠ

**Comment by item4** [comment]
@marnitto 그렇긴 한데, 그렇다고 기본 폰트로 서빙하기도 그렇지 않나 싶습니다. (...)

@sjkoon @marnitto 제 생각엔 위에 링크했던 방식으로 경량화를 시켜서 2000여자 정도의 한글 + 영문자 + 숫자 + 일반 특수문자만 하면 되지 않을까 싶은데요. 사용중인 폰트 지금의 나눔명조, 나눔펜필기도 경량화 해서 말이죠.
(문서 중간에 "똠방각하", "아햏햏" 같은걸 쓸 린 없으므로)

**Comment by sjkoon** [comment]
웹폰트는 모바일은 제외해도 될거같은데..

**Comment by item4** [comment]
@sjkoon 경량화 한번 해보고.. 팀원들 폰 중 가장 구린 제 폰으로 기다림이 참을만 한가 실험해보겠습니다.

**Comment by item4** [comment]
@sjkoon @marnitto 경량화 결과입니다.

경량화 전
-----------
* 측정 환경: Firefox, Mac OS X, 현재 snoin.com
<img width="1085" alt="2015-11-12 3 57 57" src="https://cloud.githubusercontent.com/assets/559952/11112423/4a96e89c-8956-11e5-8ee2-759da8c6aa51.png">

경량화 후
-----------
* 측정 환경: localhost, runserver로 구동한 서버. 나머진 동일.
<img width="1021" alt="2015-11-12 3 58 13" src="https://cloud.githubusercontent.com/assets/559952/11112437/64abe818-8956-11e5-8ee9-dec108e5a655.png">

**Comment by sjkoon** [comment]
결과가 고무적이네요. 이정도면 모바일에서도 좋겠읍니다.

**Comment by item4** [comment]
@sjkoon @marnitto #28 리뷰 요청드립니다
