### ISSUE TITLE
SMTP 서버

### ISSUE THREAD

**Issue by item4** [Snoin/snoin.com#20]
결정안
=====
구글 메일 서버 사용

할 일
------

* [ ] SMTP 접속 정보
* [x] 사용 가능 여부 확인

**Comment by sjkoon** [comment]
SMTP 자체 구축은 옛날과 다르게 많이 힘이 듭니다. 스팸에 대한 규정이 빡세져서..

**Comment by item4** [comment]
그럼 구글 SMTP 서버를 쓰는쪽으로 하죠

**Comment by sjkoon** [comment]
구글 메일같은 건은 안드로이드 이나 아이폰 사용시 연결이 용이하며 gmail과 설정법도 동일합니다.

**Comment by item4** [comment]
사용 가능하므로 본 서버에 API가 적용되는데로 close 하겠습니다.

**Comment by EcmaXp** [comment]
이거 된걸로 생각하고 닫겠습니다.
