### ISSUE TITLE
Our Amazing Team 해상도에 따른 프로필 사진 깨짐 문제

### ISSUE THREAD

**Issue by EcmaXp** [Snoin/snoin.com#24]
Chrome 버전 46.0.2490.80 m

(768 px? <= 창의 가로 크기 < 975 px) 가 참일 때 다음과 같은 현상이 발생합니다.
이외엔 프로필 사진의 비율은 가로 세로 1:1로 정상적으로 나옵니다.

![2](https://cloud.githubusercontent.com/assets/13285311/11034885/221dd770-8732-11e5-86d6-b7569279a72b.png)
![3](https://cloud.githubusercontent.com/assets/13285311/11034886/221ef0d8-8732-11e5-9451-5ef026bce28a.png)

**Comment by marnitto** [comment]
`/static/css/style.css:8`(Bootstrap v3.3.5)의 `#team>div>div>div>div img`에서 height가 265px로 고정되어 있는데, 이걸 제거하니까 정상적으로 보입니다.

**Comment by item4** [comment]
저희는 sass를 쓰니까 sass파일을 고치면 될 것 같습니다. 금방 고칠 수 있는 문제니 곧 PR 올릴게요

**Comment by marnitto** [comment]
네, `style.sass` 바꾸는 것까지는 저도 확인했는데 npm 설치가... ㅠㅠ 부탁드릴게요


2015-11-10 오후 6:20에 item4 이(가) 쓴 글:

**Comment by item4** [comment]
#27 에 따라 닫습니다
