### ISSUE TITLE
fetch API를 써도 되는가?

### ISSUE THREAD

**Issue by item4** [Snoin/snoin.com#3]
ajax보다 sain한 공식 구현인 fetch라는것이 있습니다.

[polyfill](https://www.npmjs.com/package/whatwg-fetch)도 있어서 IE9부터는 모두 사용하게 할 수 있습니다.

문제는 IE 6~8 인데요, IE8도 지원하는 fork도 있지만 그래도 IE6, 7은 안됩니다.

어떻게 할까요? -_-;;

**Comment by marnitto** [comment]
[w3school 브라우저 통계](http://www.w3schools.com/browsers/browsers_explorer.asp)를 보시면 아예 IE6,7에 대해선 고려조차 안 하고 있고 사용률도 굉장히 낮습니다. 정 모든 브라우저를 지원하고 싶으시다면 최대한 javascript를 사용하지 않는 방향으로 가는 게 낫겠습니다만, 제 생각에는 그런 구형 브라우저 정도는 버려도 되지 않을까 싶네요.

**Comment by LoveHoly** [comment]
IE 9 이상에서 정상 작동 하는거라면 pass해주세여

**Comment by marnitto** [comment]
@item4 제가 프알못이라... 우선 개발 속도를 빠르게 하기 위해서는 이런 세세한 부분은 구현하면서 의존성이나 한계만 정확히 명시하는 방향으로 가는 게 좋을 것 같아요. 마음대로 하셔도 상관없사옵나이다. :)

**Comment by sjkoon** [comment]
IE9 이상에서 작동이면 될거 같아요. 그 아래 보기가 힘든 세상이라

**Comment by marnitto** [comment]
@item4 마지막으로 한번 확인해주시고, 결정하시면 코멘트 + 닫기 부탁드려요.

**Comment by item4** [comment]
사용합니다
