### ISSUE TITLE
Features+ 추가하기

### ISSUE THREAD

**Issue by EcmaXp** [Snoin/snoin.com#30]
타 업체와 차별화를 두기 위해서 내세운 Python 및 Semantics, 그 이외의 팀원들과 관련하여 강점으로 내 세울 수 있는 부분들을 강조해야 된다고 봅니다. (이건 제 개인적인 생각이지만)

https://c9.io 에서 Awesome features 부분 처럼 만들어보고자 하는데 디자인은 좀 다르게 갈 예정입니다.
밑의 내용들은 대략적으로 적은것이라 다 엎어버릴 예정이고, 내용이나 문구, 이미지 등도 생각해 봐야 됩니다.

- [x] 보안성 강화 (Z보드 및 PHP를 사용하는 솔루션 대비)
- [ ] 빠른 속도 (PHP 대비)
- [ ] 빠른 로딩 속도 (minify, 웹폰트 최적화 등)
- [ ] 다양한 브라우저 지원
- [ ] 모바일 최적화 (앱 최적화는 생각해 봐야 됩니다.)
- [ ] 항상 대기중인 직원?
- [ ] 홈페이지를 만드는 개발자와 직접 상담 가능
- [ ] SERVICES 부분의 3가지 내용 전부 추가적으로 설명 또는 포함
- [ ] 국내 업체 강조 (?)
- [ ] HTTP/2 지원
- [ ] DDoS 방어 등. (CloudFlare 같은 곳과 연동 가능한가요?)

**Comment by sjkoon** [comment]
저도 @ecmaxp 님 말에 동의하고 있고 수정하겠습니다.

**Comment by item4** [comment]
@sjkoon HTTP/2 지원은 nginx 최신버전으로 올려야 가능합니다. 고객이 서버호스팅을 뭘 쓰느냐에 따라 불가능할 수도 있어요.

**Comment by sjkoon** [comment]
@item4 음 제 말은 feature들이 좀 더 구체화 되어야 할 필요가 있다는 이야기입니다.

**Comment by item4** [comment]
@sjkoon 그 부분은 저도 적극 동감합니다. 디자인상 Features는 3의 배수 갯수로 있으면 좋겠습니다.

**Comment by item4** [comment]
@EcmaXp 이슈가 분산되어서 집중이 힘듭니다. #9 에 댓글로 달고 합쳐주세요.
