### ISSUE TITLE
Service 라는 섹션명을 Features로, Services는 새로 마련

### ISSUE THREAD

**Issue by item4** [Snoin/snoin.com#32]
제목 그대로, 지금 #31 에 올라간 Service를 Feature로 바꿔버리고, Services는 따로 만들어서 웹 개발 외의 것도 다룰 수 있음을 나열하는게 어떨까 싶습니다.

Services 목록
------------------

* [ ] HTML5 퍼블리싱
* [ ] CSS3 + SCSS
* [ ] jQuery, jQuery UI
* [ ] gulp, webpack
* [ ] EcmaScript 6 with babel
* [ ] Python 3
* [ ] Flask, SQLAlchemy
* [ ] Celery, RabbitMQ
* [ ] py.test
* [ ] requests, lxml
* [ ] sphinx
* [ ] MySQL, MariaDB
* [ ] PostgreSQL
* [ ] Click, Demonize
* [ ] Apache2, Nginx
* [ ] uWSGI, gunicorn
* [ ] TCP Server/Client
* [ ] PHP 5, PHP 7

**Comment by EcmaXp** [comment]
제가 원한게 이런거였습니다!

**Comment by sjkoon** [comment]
제가 원한게 이런거였습니다!

**Comment by item4** [comment]
@Snoin/owners 더 추가해야합니다. 굳이 체크는 달 필요 없고 목록 더 추가해주세요.

**Comment by item4** [comment]
본 이슈의 구현은 #31 이 머지되고 난 다음에

**Comment by EcmaXp** [comment]
HTML5 퍼블리싱 - fa-html5
 CSS3 + SCSS - fa-css3
 jQuery, jQuery UI - fa-qrcode
 gulp, webpack - fa-archive
 EcmaScript 6 with babel - fa-bell
 Python 3 - fa-file-code-o
 Flask, SQLAlchemy => fa-flask, fa-database?
 Celery, RabbitMQ => fa-tasks
 py.test => fa-list
 requests, lxml => fa-level-up
 sphinx => fa-file-text-o
 MySQL, MariaDB => fa-database
 PostgreSQL => fa-database [??
 Click, Demonize => fa-cog
 Apache2, Nginx => fa-server
 uWSGI, gunicorn => fa-cloud
 TCP Server/Client => fa-connectdevelop
 PHP 5, PHP 7 => fa-code

임의의 아이콘으로 구성했습니다. 차후 아이콘 변경이 필요해 보입니다.
https://fortawesome.github.io/Font-Awesome/cheatsheet/

**Comment by item4** [comment]
아이콘은 좀 바꿀 필요가 있어 보입니다

**Comment by sjkoon** [comment]
아이콘은 아무래도 자체제작 해야될까요?

**Comment by marnitto** [comment]
분류가 아닌 세부기술을 언급하는 거면 기존의 아이콘보다 CI를 쓰는 게 좋지 않을까요?

**Comment by sjkoon** [comment]
저도 추상화된 아이콘보단 CI를 쓰는게 낫다고 보거든요

**Comment by item4** [comment]
CI에 저작권이 있는 경우가 왕왕 있습니다.

일일히 확인해야한다는 문제가 있네요.

**Comment by sjkoon** [comment]
간단히 텍스트로 해도 이쁠거같지 않나요

**Comment by item4** [comment]
사실 고객들이 눈에 보이는 무언가에 혹할 것 같긴 하지만, 아이콘때문에 스크롤이 너무 길어지면 본말전도라고 생각합니다.

@EcmaXp 아이콘 빼고는 예쁘게 나열할 방법이 없을까요

**Comment by EcmaXp** [comment]
텍스트만 있는데 마우스를 올리면 아이콘이 위로 생긴다던가.. 하면 어떤가요
(또는 백그라운드로 투명도 넣어서 넣는 방법도 있음)

그런데 막상 아이콘을 넣어도 CI 때문에 문제 일 것 같네요.

**Comment by marnitto** [comment]
로고는 지적재산권에 의해 보호받는 저작물이고, 우리는 영리를 목적으로 하는 사이트를 작성하고 있으므로, CI 사용 시에는 거의 모두 허가를 받아야 할 것으로 보입니다. :fearful: 

@EcmaXp 님 제안 중 hover가 좋아보이는데, 아이콘을 올리면 텍스트를 보여주는 식이 더 낫지 않을까요?

**Comment by sjkoon** [comment]
음 제가 말한 텍스트는  현재 아이콘의 색상 동그라미 안에 텍스트로 하는 이야기였음다 ㅎㅎ

2015년 11월 18일 오전 12:00, marnitto <notifications@github.com>님이 작성:

**Comment by item4** [comment]
논의 요약
-----------

현재 Service가 너무 많음. 큰 항목으로 묶어서 정리할 것
예: Database - pgsql, mysql, mariadb
묶어서 정리하는 작업은 @item4 가 1차적으로 한 후 @sjkoon 이 검수 예정

웹 디자인 시안
------------------
![image](https://cloud.githubusercontent.com/assets/559952/11325390/c7aa560c-918f-11e5-9503-440838de55e6.png)
이런 느낌으로

**Comment by item4** [comment]
@Snoin/owners 3*2 배열을 염두하고 만들어 보았습니다.

아이콘의 적합성도 확인 부탁드립니다.

Web Frontend
-------------------
* icon: [fa-html5](http://fortawesome.github.io/Font-Awesome/icon/html5/)
* HTML5
* CSS3
* jQuery
* jQuery UI

Web Backend
-------------------
* icon: [fa-cogs](http://fortawesome.github.io/Font-Awesome/icon/cogs/)
* Python 3
* Flask
* SQLAlchemy
* uWSGI, gunicorn
* PHP 5, PHP 7

Web Technologies
-------------------------
* icon: [fa-flask](http://fortawesome.github.io/Font-Awesome/icon/flask/)
* SCSS
* gulp
* webpack
* EcmaScript 6

Quality Assurance
-------------------------
* icon: [fa-refresh](http://fortawesome.github.io/Font-Awesome/icon/refresh/)
* Git, GitHub
* py.test
* Sphinx

Server-side Application
-------------------------------
* icon: [fa-terminal](http://fortawesome.github.io/Font-Awesome/icon/terminal/)
* Celery
* requests, lxml
* Click
* Demonize
* TCP Server/Client

Server Management
---------------------------
* icon: [fa-server](http://fortawesome.github.io/Font-Awesome/icon/server/)
* MySQL, MariaDB
* PostgreSQL
* RabbitMQ
* Apache2
* Nginx

**Comment by EcmaXp** [comment]
Server-side Application의 fa-terminal을 제외한 나머지는 만족합니다.

**Comment by sjkoon** [comment]
저도 문제 없다고 생각함..

**Comment by item4** [comment]
IRC에서 전면 재개편하기로 했는데 아예 흐름이 다르므로 이슈 닫습니다
