### ISSUE TITLE
PR 자동 반영 시스템

### ISSUE THREAD

**Issue by EcmaXp** [Snoin/snoin.com#33]
PR 자동반영 (반영된 PR 들을 위해서)
-----------------------------
PR 반영되면 snoin.com도 자동으로 최신버전으로 업데이트 하는 건 어떤가요.
물론 차선책으로는 별도의 홈페이지를 뒀다가 일정시간이 지나면 메인도 자동으로 반영되는 방법도..

**Comment by item4** [comment]
이 이슈는 둘로 쪼개는게 좋을 것 같습니다.

**Comment by EcmaXp** [comment]
넵

**Comment by item4** [comment]
이 부분은 사실 ~~travis가 쓰기 귀찮아서~~ 안했던건데, 이쯤 됬으니 만들어도 되지 않나 싶기도 합니다.

* [ ] deploy용 snoin.com 계정
* [ ] 서버 리스타트 권한
* [ ] deploy 스크립트

deploy 스크립트가 문제인데요.. py3에서 올리려면 [invoke](http://www.pyinvoke.org/)란걸 써야합니다.
아니면 sh 스크립트로 올리던가요

**Comment by marnitto** [comment]
Travis나 CircleCI에서도 deploy 기능을 제공해주지만, 이걸 어떤 식으로 버전 관리할지부터 먼저 생각해봐야 할 듯합니다.
Private key나 비밀번호를 github에 저장하면 요긴하게 써먹을 사람들이 한둘이 아니거든요(...).

invoke는 지금 내용과는 별개로 보입니다. 우선은 deploy를 어떻게 안전하고 편하게 사용할 수 있는지에 집중하고, 서버 단에서의
(graceful) retsart, building은 나중에 보시는 게 어떨까요.

**Comment by EcmaXp** [comment]
PR 미리보기 시스템과는 다르게, Travis-CI에서 [암호화된 환경변수](http://docs.travis-ci.com/user/environment-variables/#Encrypted-Variables) 를 이용하면 될 듯 합니다.

**Comment by item4** [comment]
PR일땐 올라가면(deploy) 안되고, 심지어 환경변수값을 읽을 수 있어서도 안됩니다.

그 부분을 조심해서 짜면 될 것 같네요.

위에서 언급한 것 중 2가지는 @sjkoon 이 발급해주셔야 합니다.

**Comment by EcmaXp** [comment]
정확히 PR일 때에는 Travis-CI에서 암호화된 환경변수를 아예 제공하지 않습니다.
별 걱정 없을 것 같지만 해당 사항 참고해서 개발하면 될 듯 합니다.

**Comment by marnitto** [comment]
용례를 좀더 명확히 해야 합니다. PR을 올린 상태에서 사이트 업데이트를 자동으로 한다는 말씀인가요, 아니면 PR이 머지되면
업데이트한다는 말씀인가요? 전자의 경우 travis를 쓰기 애매하면 buildbot같은 별도 툴을 쓰는 방법이 좋을 듯합니다.

**Comment by EcmaXp** [comment]
PR 머지시 입니다.

**Comment by item4** [comment]
논의 요약
------------
ssh를 통한 자동 빌드는 @sjkoon 의 결정에 따라 없는 일로
다음 두 가지 대안을 제시

1. crontab으로 주기적으로 빌드
2. webhook으로 빌드

**Comment by item4** [comment]
@Snoin/owners 향후 웹 개발에도 영향을 줄 의사결정으로 보이니 각자 의견 주세요

**Comment by marnitto** [comment]
merge시면 webhook으로 가능합니다. crontab은 별로 좋은 선택으로 보이진 않네요.

**Comment by sjkoon** [comment]
이 부분 ssh 자동빌드 계정 따로 있으니 작업시 저에게 메시지 주세요.

**Comment by item4** [comment]
sjkoon 의 의향 변경으로 ssh를 쓰는 방향으로 변경되었습니다.
