### ISSUE TITLE
PR 미리보기 시스템

### ISSUE THREAD

**Issue by EcmaXp** [Snoin/snoin.com#34]
PR 미리보기 (PR가 아직 반영되지 않는 경우)
--------------------------------------
홈페이지 자동 스크린 캡쳐를 생각했었는데 제가 PhantomJS를 사용하려고 해봤으나 잘 되지 않는 관계로, 반영될 PR 패치 같은 것들도 자동으로 서브 도메인 등의 방법을 통해서 호스팅 되면 괜찮을 것 같습니다.
(webhook 이용해서, 다만 이 경우엔 별도의 게이트를 둬서 자동으로 홈페이지 생성 후 일정 시간 경과시 자동으로 해체...?)

**Comment by item4** [comment]
이미지를 댓글로 다는건 어려운가요 역시

**Comment by EcmaXp** [comment]
지금 방금 해봤는데 phantomjs 되서, 이미지를 올릴곳만 찾으면 될 것 같습니다.

**Comment by item4** [comment]
파일창고를 살려버리면 좋겠지만 그건 힘들 것 같고, imgur 어떤가요

**Comment by EcmaXp** [comment]
http://cloudinary.com/

**Comment by item4** [comment]
@sjkoon 이 작업을 하려면 snoin 전용 봇 계정이 필요합니다.

**Comment by EcmaXp** [comment]
http://res.cloudinary.com/ecmaxp/image/upload/v1447776656/hbiatm9pyfkwwghucipw.png
너비는 확장하면 되지만 글자가 깨집니다. 폰트 수정이 필요해 보입니다.
아마도.. phantomjs에서 웹폰트를 지원하지 않는 것 처럼 보이기도 합니다.

**Comment by EcmaXp** [comment]
PhantomJS에서 웹폰트를 지원하지 않으면, fallback 폰트를 지정하고 이미지 상 가독성은 살짝 포기해야 합니다.

**Comment by EcmaXp** [comment]
https://res.cloudinary.com/ecmaxp/image/upload/v1447780016/qsebazf6wpsut4h5nvnm.png
빌드는 실패했고, 화면은 키웠습니다.

**Comment by EcmaXp** [comment]
Status API 이용해서 코멘트를 올리기 보단 바로 링크 확인가능 하도록 하는게 좋을 것 같습니다.
https://developer.github.com/v3/repos/statuses/

**Comment by marnitto** [comment]
PhantomJS가 브라우저에서 보여주는 것만큼 깔끔하게 스크린샷이 나올 수가 없습니다. 특히 웹폰트 및 브라우저별 화면 구성 테스트를
위해서는 더더욱 안 맞아요. 차라리 [Selenium](http://www.seleniumhq.org/)을 활용해서, VM 안에 필요한
브라우저들을 설치해두고 사이트에 접속해서 스크린샷을 찍거나, [BrowserStack](
https://www.browserstack.com/screenshots)처럼 외부 서비스를 이용하는 게 좋아보입니다. 우리가
자체적으로 구축한다면 서브프로젝트로 빼놓고 활용해야겠네요.

이 건은 얘기하다 보면 점점 산으로 가는 것 같은데, 이왕 하는 거라면 제대로 해도 향후 업무 활용도 면에선 나쁘진 않을 것 같습니다.

**Comment by EcmaXp** [comment]
Moonrise님 도움으로 64비트 리눅스 머신에서 작동가능한 PhantomJS v2.0.0 을 확보했습니다.

- [x] 웹폰트 지원
- [x] 다양한 해상도 지원 (viewport 설정 가능)
- [ ] 다중 브라우저 지원

**Comment by EcmaXp** [comment]
더 해야 될 작업으로는
- [ ] API 키 암호화 (PR에서도 사용 가능하도록)
- [ ] Status API 지원

이 있으며 요약하자면 별도의 API 서버를 만들어야 된다는 결론이 나옵니다.
(최소한의 인증 및 권한 유지로 파일 업로드와 Status 반영하는 별도의 API 서버)

오늘과 내일은 휴일이고 저도 바쁜만큼 월요일에 생각해봅시다.

**Comment by marnitto** [comment]
이슈의 기본 목적인 PR별 자동 스크린샷은 완료되었으니, 추가적으로 보완할 사항은 여기를 참조 달아서 새로 이슈를 만들어 관리하는 게 좋아보입니다. 고생 많으셨습니다. :+1:

@EcmaXp @item4 이견 없으시면 내일 오전 중으로 이 이슈 닫겠습니다.

**Comment by item4** [comment]
네
