### ISSUE TITLE
코딩 컨벤션 통일

### ISSUE THREAD

**Issue by item4** [Snoin/snoin.com#36]
안내
====
본 논의는 앞으로 Snoin에서 개발하는 모든 개발품에 적용됩니다.

Python
---------
* PEP-8 준수
* import order를 a-z 순으로 → [import-order](https://pypi.python.org/pypi/import-order/0.0.5)를 hook과 CI에 추가 (DIFF가 쓸데없이 발생하지 않도록 하기 위한 강제)
* import 규칙 제정 (무엇을 `import ~` 로 할지, 무엇을 `from ~ import ~`로 할지)
* `__all__` 변수 사용 의무화 (논의 필요)
* `from ~ import *` 금지 (전역 스코프를 망침)
* type annotation 사용 (논의 필요)
* flake8 사용 강제, hook, CI 추가
* str.format 사용 강제 (논의 필요)

HTML
---------
* tab = 2 space로 할 것 (논의 필요)
* self-closing tag를 xml 스타일로 사용 금지 (`<br />` 꼴의 사용 금지)

JavaScript
---------------
* tab = 2 space로 할 것 (논의 필요)
* `;` 생략 금지

SCSS (CSS)
-----------------
* tab = 2 space로 할 것 (논의 필요)
* 1 line에 1개의 속성만 지정하고 개행
* 속성명 순으로 정렬
* `@extend`, `@include`, 속성, 자손 배열 규칙 (논의 필요)

**Comment by item4** [comment]
Python에 추가

* `from ~ import *` 금지 (전역 스코프를 망침)

**Comment by item4** [comment]
Python에 추가

* type annotation (논의 필요)

**Comment by marnitto** [comment]
코드 너비는 반드시 80글자 기준으로 맞추나요? HTML/CSS는 2칸 들여쓰기 처리해도 힘들 것 같은데...

**Comment by item4** [comment]
@marnitto Python만 길이 제한하고 나머지는 그냥 두는게 좋을 것 같습니다.

**Comment by marnitto** [comment]
넵.

type annotation은 docstring만으로 충분하고, 파이썬의 장점인 유연한 코딩을 막는다고 생각해서 반대합니다. 타입 체킹하는 코드를 쓰려면 C#이나 Java를 쓰는 게 더 낫지 않을까 싶네요.

**Comment by item4** [comment]
type annotation을 쓰면 docstring을 읽을 줄 모르는 에디터도 type annotation을 파싱할 줄 알면 인자를 잘못 넣었다던가 하는 부분을 알아서 캐치해준다는 장점이 있긴 한데요..

애매하군요. docstring, type annotation 지원하는 에디터가 pycharm 계열 뿐이라서 (...)

**Comment by marnitto** [comment]
전 죄스럽게도(….) PyCharm같은 파이썬에 특화된 에디터를 쓰진 않는지라… 이런 애매한 부분은 우리의 문서화 능력을 믿어도 되지 않을까요

**Comment by item4** [comment]
CSS, SCSS 추가

* 1 line에 1개의 속성만 지정하고 개행
* 속성명 순으로 정렬

SCSS 추가

* `@extend`, `@include`, 속성, 자손 배열 규칙 (논의 필요)

JavaScript 추가

* `;` 생략 금지

**Comment by item4** [comment]
HTML 추가
* self-closing tag를 xml 스타일로 사용 금지 (`<br />` 꼴의 사용 금지)

**Comment by marnitto** [comment]
CSS / SCSS에서 `!important` 사용 금지는 안 거는 게 괜찮겠죠? 이게 silver bullet처럼 쓰이는 건 알지만 그래도 정말 이거 아니면 답이 없을 떄도 있어서요.

**Comment by item4** [comment]
`!important`에 대해선 최대한 안쓰는 것이 잘 만든 CSS라고 생각하고 있긴 합니다.

필요할때만 쓰는 편이 좋을 것 같습니다.

**Comment by item4** [comment]
Python 추가
* flake8 사용 강제, hook, CI 추가

**Comment by EcmaXp** [comment]
파이썬 부분에서 str.format 는 어떤가요. (% 연산자 대신)

**Comment by item4** [comment]
애지간한건 다 추가된 것 같으니 `논의 필요`들에 대한 제 의견을 적어보겠습니다.

import 규칙 제정
---------------------

기본: 모듈 레벨이 1단계인 것은 `import`로, 2단계 이상인 것은 `from ~ import ~`로
```py
# 모두 1단계
import json
import subprocess

import pytest

# 2단계 → from import
from urllib.parse import quote

from sqlalchemy.orm.session import sessionmaker
```

변형1: 단어 길이가 짧은 내장 module에 한해서는 2단계를 넘더라도 `import`를 허용

```py
import os.path
```

변형2: 외부 모듈 (서드파티)에 대해서는 가독성을 위한 부분에서는 1단계에서도 `from ~ import ~`를 허용. 단, 객체명이 모호해지는 경우엔 불허함

```py
from flask import Flask, request  # OK
from yaml import loads # No!!
```
변형3: 내부 참조는 모두 `from ~ import ~`

```py
from .config import load_config
```

__all__ 변수 사용 의무화
-------------------------------
찬성
이유: Sphinx가 인식하는 범위에 영향을 줌 (기껏 짠 소스가 문서화가 안 될수도 있음)

type annotation 사용
---------------------------
기권
이유: 마니또님 의견도 타당하다고 생각

tab = 2 space로 할 것
----------------------------
HTML: 찬성 → 중첩 관계가 너무 많아지므로
JavaScript: 찬성 → 언어의 특성상 필요하다 생각
SCSS: 찬성 → 가독성

`@extend`, `@include`, 속성, 자손 배열 규칙
--------------------------------------------------------
`@extend` → `@include` → 속성 → media query → 자기 변형(`&` 연산자) → 직계 자손(자식) → 자손 순으로

```scss
ul {
  @extend .row;

  @include zebra();

   width: 50px;

  @media (min-width: 1000px) {
      width: 150px;
  }

  &:hover {
    background: #aaa;
  }

  > li {
    margin: 0;
  }

  a {
    color: red;
  }
}
```

str.format 사용 강제
-------------------------
찬성
이유: 보다 나은 가독성을 추구할 수 있음.

**Comment by EcmaXp** [comment]
전 개인적으로 4 spaces 가 좋지만 2 spaces 하죠.

**Comment by item4** [comment]
본 논의는 21일 0시 (KST)까지 진행 후 의견들을 총합해서 고정합니다

**Comment by EcmaXp** [comment]
고정하기보다는 지속적으로 통합하는게 나을 듯요.

**Comment by item4** [comment]
@EcmaXp 일단 1차 취합이 목적이었는데, 댓글 수정할게요

**Comment by marnitto** [comment]
초안 정해지면 PR로 CONTRIBUTING.md 올리면서 수정하면 될 듯합니다.

**Comment by EcmaXp** [comment]
이름 관련 규칙들도 정해야 될듯요.
기본적으로는 언어에서 주로 사용하는 이름 규칙을 사용하는 걸로...
ex) 파이썬에서는 대문자 보다는 _를 많이 사용하죠..

**Comment by item4** [comment]
본 Issue는 `CONTRIBUTING.md`을 만드는 PR이 merge된 후에 Close합니다.

추후 논의가 필요한 경우엔 `CONTRIBUTING.md`에 대한 PR을 보내고, 해당 thread에서 논의하면 좋겠습니다.
