### ISSUE TITLE
Snoin 내부 논의/정보 보관용 저장소 

### ISSUE THREAD

**Issue by item4** [Snoin/snoin.com#38]
seektam 진행시엔 trello를 사용했는데, Snoin 전역적으로 쓸 공간이 하나 필요합니다.

그냥 trello를 하나 만들어버리는 방식으론 의미가 없다고 생각하기에 논의를 했으면 합니다.

**Comment by sjkoon** [comment]
전에 trac이란걸 써본적이 있는데.. 흠

**Comment by item4** [comment]
서버 설치형으로, redmine이란 툴도 존재하는 걸로 압니다. 다만 디자인이 구리다는 치명적인 결함이..

**Comment by marnitto** [comment]
Github 외의 수단을 사용할 일이 있을까요? 비밀로 유지해야 할 내용을 관리하는 것 때문이신지...

**Comment by item4** [comment]
@marnitto 고객정보, 보안이 필요한 정보 등을 깃헙에 공개적으로 올려서 유출시킬 수는 없으니까요..

**Comment by sjkoon** [comment]
아무래도 github 외에 private한 공간이 필요한 부분에 대해선 공감하고.. redmine 좀 알아봐야겠네요.

**Comment by marnitto** [comment]
다소 설치하기 편한 몇 가지를 더 소개합니다.

  * [Gitlab](https://about.gitlab.com/): Github만큼 깔끔한 인터페이스가 특징입니다. [Docker로 설치](http://www.damagehead.com/docker-gitlab/)할 수 있습니다.
  * [Phabricator](https://phacility.com/phabricator/): Github이 프로젝트 관리에 촛점이 맞춰져있다면, 이거는 이슈 관리, 마일스톤 등 프로젝트 관리에 촛점이 맞춰져 있습니다. PHP 애플리케이션이고, LAMP stack이 필요합니다.

**Comment by sjkoon** [comment]
Docker은 올라갔습니다.

**Comment by EcmaXp** [comment]
Gitlab +1

**Comment by marnitto** [comment]
Gitlab 쪽으로 촛점 맞추겠습니다.

@sjkoon Gitlab docker 구성을 보면 PostgreSQL과 Redis가 있는데요, Redis는 Docker로 돌려도
상관없지만 postgresql은 docker로 돌리셔도 되고 직접 관리하시기 쉽게 native에서 돌리는 방법이 있습니다. 어떻게 하고
싶으세요?

**Comment by sjkoon** [comment]
native는 뭐쓰는건가요? MariaDB?

**Comment by marnitto** [comment]
아뇨, PostgreSQL을 돌리는 건 같은데 이걸 직접 돌릴지 docker 위에서 돌릴지의 차이에요.

**Comment by item4** [comment]
그보다, 논의/정보 저장용으로 gitlab이 적합한지가 궁금한데요.

코드를 저장할 수 있다는 점에선 좋지만 그 외에 이슈 관리가 수월한지 궁금합니다.

**Comment by marnitto** [comment]
이슈 관리만 놓고 봤을 때에는 Gitlab이 Github과 비슷합니다. Phabricator는 이슈 관리 및 마일스톤에 촛점이 맞춰져있고, 프로젝트 단위로 관리할 수 있는 기능이 더 있죠. 내부 위키를 놓고 본다면 Gitlab이 더 
익숙하겠네요. 구체적으로 어떤 기능이 더 필요하신지 말씀해주시면 요구사항에 맞게 솔루션을 찾아보도록 하겠습니다.

**Comment by item4** [comment]
snoin 전용 계정 비밀번호 공유라던가 하는 시큐어한 정보를 다룬다거나, 고객 의뢰가 들어왔을때 회의 기록 정도를 생각했습니다.

**Comment by marnitto** [comment]
데이터를 어떻게 저장할지가 문제인데… 뭐 러프하게 가면 dropbox를 써도 됩니다만 Gitlab 에 첨부파일 올리기 <https://github.com/gitlabhq/gitlabhq/issues/2180>로 충분하지 않을까요?

​

**Comment by sjkoon** [comment]
Gitlab 생성되었으므로 Close
