### ISSUE TITLE
잡다한 의존성 제거

### ISSUE THREAD

**Issue by item4** [Snoin/snoin.com#4]
* [x] classie.js (jq로 대체 가능)
* [ ] contact_me.js (새로 구현해야함)
* [x] cbpAnimatedHeader.js (classie 의존성 고치면서 새로 구현)
* [x] jqBootstrapValidation.js (그냥 두기로)

**Comment by item4** [comment]
2개 처리 완료 (classie.js, animated header)

**Comment by item4** [comment]
jqBootstrapValidation.js는 그냥 둡시다.
form validation을 새로 짜기도 솔직히 낭비같다는 느낌이 드네요.

**Comment by EcmaXp** [comment]
된 것으로 생각하고 닫겠습니다.
