### ISSUE TITLE
pre-commit hook 작성

### ISSUE THREAD

**Issue by item4** [Snoin/snoin.com#40]
* [x] flake8
* [x] import-order
* [x] 의존성 목록에 추가
* [x] travis 검사 추가

**Comment by marnitto** [comment]
개발자들이 개발 환경을 모두 제대로 구성한다고 가정하면, 커밋 훅으로 travis를 다는 것보다 unittest를 자체적으로 돌리게
하는 게 훨씬 더 피드백이 빠르지 않을까요?

**Comment by item4** [comment]
@marnitto 뭔가 용어 전달이 꼬인 것 같은데, travis에도 commit hook으로 쓰는 것을 검사에 추가해서 만에 하나 hook을 달지 않고 올린 PR이 lint를 깨먹는 경우를 방지했습니다. #41 의 `.travis.yml` 구현을 참고해주세요.
