### ISSUE TITLE
powebscr/phantomjs 파일에 대해서

### ISSUE THREAD

**Issue by item4** [Snoin/snoin.com#42]
너무 대용량 파일이 버티고 있어서 clone, pull, push에 영향을 줍니다.

다른 보관 방법이 없을까요?

**Comment by sjkoon** [comment]
라이브러리인가요? 만약 그렇다면 링크나.. 따로빼놓는게 어떨지

**Comment by marnitto** [comment]
따로 x86_64용으로 컴파일해서 넣은 걸로 알고 있습니다.

**Comment by item4** [comment]
@marnitto travis 환경은 ubuntu니까 `apt-get`이 사용 가능한데, 그것으로 어떻게 안 될까요?

**Comment by marnitto** [comment]
phantomjs를 따로 테스트해서 설치하는 방안을 생각해보고, 되는 대로 다시 댓글 달겠습니다. 여담으로 이쯤하면 [Docker](https://www.docker.com/)나 [Vagrant](https://www.vagrantup.com/)를 고려할 때가 되지 않았나 싶네요.

```
[marnitto@rpi snoin.com]$ git push origin master
Counting objects: 106, done.
Compressing objects: 100% (105/105), done.
Writing objects: 100% (106/106), 25.46 MiB | 2.51 MiB/s, done.
Total 106 (delta 51), reused 0 (delta 0)
remote: warning: GH001: Large files detected. You may want to try Git Large File Storage - https://git-lfs.github.com.
remote: warning: See http://git.io/iEPt8g for more information.
remote: warning: File powebscr/phantomjs is 53.96 MB; this is larger than GitHub's recommended maximum file size of 50.00 MB
To git@github.com:marnitto/snoin.com.git
   036ce16..e2575bc  master -> master
```

**Comment by marnitto** [comment]
[Ubuntu package](https://launchpad.net/ubuntu/+source/phantomjs)를 참조해서 `apt-get`으로 다운로드받을 수 있는 phantomjs 버전은 1.9입니다. 기존에는 웹폰트 지원, libicu, openssl 라이브러리 연동 등의 문제로 2.0을 정적 컴파일해 사용한 상황이고요. ppa를 추가로 등록시키는 방법은 우분투 14.04에서만 적용 가능해서 별 효과가 없어보입니다.

[Docker에서 phantomjs 2.0.0을 사용할 수 있게 빌드](https://hub.docker.com/r/wernight/phantomjs/)해놓은 예제가 있습니다. 이걸 사용하면 버전 관리는 깔끔해지는데, 이미지 크기가 364MB라서 테스트가 굉장히 느려질 수가 있습니다. 직접 테스트해보고 정 아니다 싶으면 travis 환경에 맞게 어느 정도 최적화 작업 진행하면 되겠습니다.

**Comment by EcmaXp** [comment]
확인해보겠습니다.

**Comment by EcmaXp** [comment]
asdf...

**Comment by marnitto** [comment]
```
<marnitto> EcmaXp: 
<EcmaXp> ?
<EcmaXp >아
<EcmaXp> ㅈㅅ
<marnitto> 저 최소한 이번 주 수요일까지는
<EcmaXp> asigge
<EcmaXp> 네
<marnitto> 스케줄이 꽉차있어서
<marnitto> 목요일부터 볼게여
<EcmaXp> 그거 여러 명 설정 안되나요
<EcmaXp> 한명만 되는거였나
<EcmaXp> ...
<marnitto> ? 될텐데여
<EcmaXp> 저 눌렀더니 님 풀리고 저 되서
<EcmaXp> 당황했음
<marnitto> 님 하세요 그럼
```

@EcmaXp 파이팅! (??)

**Comment by EcmaXp** [comment]
https://github.com/Snoin/powebscr 에서 계속 개발을 진행합니다.
해당 개발이 완료하는 대로 이 파일은 삭제하도록 하겠습니다.

**Comment by EcmaXp** [comment]
#63
