### ISSUE TITLE
Team 정보 완성

### ISSUE THREAD

**Issue by item4** [Snoin/snoin.com#5]
* [x] @sjkoon 
* [x] @marnitto 
* [x] @LoveHoly 
* [x] @item4
* [x] @ecmaxp

**Comment by marnitto** [comment]
제 경우에는 Team 정보에 지금 작성하신 거 이상 들어갈 게 없어보이는데, team 정보 안에 구체적으로 어떤 게 들어갔으면 좋겠다고 생각하시나요?

**Comment by item4** [comment]
@marnitto 사진이요. 지금 팀원 프로필이 대부분 익명 이미지인데, 그마저도 마니또님껀 뭘 넣을지 몰라서 방치 상태(...) 팀의 신뢰도 향상을 위해 가급적 실사가 좋지 않을까 생각하는ㄷ..

**Comment by marnitto** [comment]
전 저 사진 굉장히 마음에 드는데.... 프로필용 사진 하나 찍어야겠네요. 우선은 트위터 프사나 요거 쓰셔도 상관없습니당.

**Comment by marnitto** [comment]
이거 실서버에 반영 다 되는 대로 close하는 게 좋지 않을까요?

**Comment by item4** [comment]
아, 다 되었군요. 게멩님을 넣자는 의견이 있지만 일단 게멩님이 의견 불충분 상태같으므로 일단 닫습니다.
