### ISSUE TITLE
라이센스 변경

### ISSUE THREAD

**Issue by item4** [Snoin/snoin.com#61]
지금 [Apache License 2.0](http://www.apache.org/licenses/)으로 되어있는데, 사실 이건 디자인 원본의 라이센스일 뿐이므로 굳이 이걸 써야할 이유는 없지 않나 싶습니다.

뭐가 좋을까요?

* AGPLv3
* MIT
* Apache2.0 (현행)

**Comment by sjkoon** [comment]
AGPLv3

**Comment by marnitto** [comment]
저도 AGPLv3에 동의합니다.

2015-12-09 9:11 GMT+09:00 Sangjin Cho <notifications@github.com>:

**Comment by EcmaXp** [comment]
AGPLv3 +1
