### ISSUE TITLE
IRC에 Issue 변화 알림

### ISSUE THREAD

**Issue by item4** [Snoin/snoin.com#62]
메일로도 오지만, IRC에도 알림이 왔으면 좋겠습니다.

아예 봇이 하나 필요할 것 같은데 어떻게들 생각하시나요?

**Comment by EcmaXp** [comment]
찬성, 누가 하죠?

**Comment by EcmaXp** [comment]
나인가?

**Comment by marnitto** [comment]
그 열정 응원하겠습니다 :)

**Comment by marnitto** [comment]
다른 사람한테 일만 맡기고 도망가기엔 도저히 양심이 용납치 않아, 몇 가지 도움이 될 만한 모듈을 소개해드립니다.

   * [schedule](https://pypi.python.org/pypi/schedule): Crontab 대용입니다. 예제 코드 보시면 알겠지만 정말 깔끔합니다. 근데 이거 webhook 받을 거면 필요없어보이는데...
   * [irc](https://pypi.python.org/pypi/irc)
   * [requests](http://docs.python-requests.org/en/latest/): http 클라이언트 라이브러리입니다.
   * [Github Webhook](https://developer.github.com/webhooks/)
   * [Github API](https://github.com/dustin/py-github)
   * [Flask](http://flask.pocoo.org/)
   * [Celery](http://www.celeryproject.org/) 백그라운드 프로세싱의 기본이죠.

...음 뭔가 모듈을 쓰다 보니 점점 산으로 가네요. 정 그러시면 나중에 Assigner 저로 바꾸셔도 상관없습니다.

**Comment by marnitto** [comment]
다른 사람한테 일만 맡기고 도망가기엔 도저히 양심이 용납치 않아, 몇 가지 도움이 될 만한 모듈을 소개해드립니다.
  * [schedule](https://pypi.python.org/pypi/schedule): Crontab 대용입니다. 예제 코드 보시면 알겠지만 정말 깔끔합니다. 근데 이거 webhook 받을 거면 필요없어보이는데...
  * [irc](https://pypi.python.org/pypi/irc)
  * [requests](http://docs.python-requests.org/en/latest/): http 클라이언트 라이브러리입니다.
  * [Github Webhook](https://developer.github.com/webhooks/)
  * [Github API](https://github.com/dustin/py-github)
  * [Flask](http://flask.pocoo.org/)
  * [Celery](http://www.celeryproject.org/) 백그라운드 프로세싱의 기본이죠.

...음 뭔가 모듈을 쓰다 보니 점점 산으로 가네요. 정 그러시면 나중에 Assigner 저로 바꾸셔도 상관없습니다.

**Comment by EcmaXp** [comment]
https://gist.github.com/EcmaXp/870e7c0802e8423f9877

**Comment by EcmaXp** [comment]
일단은 제 24시간 동작하는 개인 서버에서 돌리겠습니다.
차후 필요시에는 스노인 서버에서 돌려도 될 듯 합니다. (코드는 약간 수정해야 됩니다.)

**Comment by EcmaXp** [comment]
실제로 사용하시다가 고치고 싶으신 분은
https://gist.github.com/EcmaXp/870e7c0802e8423f9877#file-track-py-L11

이 부분 변경하셔서 저에게 알려주시면 고치겠습니다.

**Comment by EcmaXp** [comment]
```
[23:03:52] <i7-5775C> item4
[23:03:58] <i7-5775C> 지금 리포로 설정된 webhook
[23:04:06] <i7-5775C> 그냥 org로 올려놓을까요
[23:04:47] <sigsrv^bot> [snoin.com] EcmaXp comment created on issue #63: powebscr 대체 / 서브모듈화 (https://github.com/Snoin/snoin.com/issues/63#issuecomment-162889564)
[23:05:16] <item4> i7-5775C, 그그 컨벤션에 맞춰서
[23:05:18] <item4> 정리만 하면
[23:05:22] <item4> 올려도 될 것 같아요
[23:05:26] <i7-5775C> 컨벤션에 맞춘다는게
[23:05:28] <i7-5775C> 어떤말이죠
[23:05:30] <item4> 그리고 그바기는 피를 토했다
[23:05:36] <i7-5775C> 아
[23:05:37] <i7-5775C> 아!!!
[23:05:37] <i7-5775C> 맙소사
[23:05:38] <item4> CONTRIBUTING.rst
[23:05:46] <i7-5775C> 나중에 시간나면 고치죠
```

**Comment by sjkoon** [comment]
네 안정화 되면 서버에서 돌리도록 하겠습니다.

**Comment by EcmaXp** [comment]
추가 의견 없으면 제 임의로 메세지 작성 후 서버에서 돌리도록 하겠습니다.

**Comment by EcmaXp** [comment]
이 이슈와 관련 된 내용은 https://github.com/Snoin/whipbot/issues/2 에서 계속 다루겠습니다.
