### ISSUE TITLE
powebscr 대체 / 서브모듈화

### ISSUE THREAD

**Issue by EcmaXp** [Snoin/snoin.com#63]
https://github.com/Snoin/powebscr

아직 phantomjs를 사용하고 있기 때문에 sudo를 풀 수는 없습니다. 참고 바랍니다.

**Comment by EcmaXp** [comment]
참고로 전 서브모듈을 쓸 줄 모릅니다.

**Comment by marnitto** [comment]
Git submodule은 Bitbucket의 subrepo처럼 다른 저장소를 import하는 기능입니다. 지금 powebscr
저장소를 따로 관리하고 있으니, powebscr이 안정화되는 대로 모듈 링크하면 돼요.

https://git-scm.com/book/ko/v1/Git-%EB%8F%84%EA%B5%AC-%EC%84%9C%EB%B8%8C%EB%AA%A8%EB%93%88

**Comment by EcmaXp** [comment]
네 알겠습니다.

**Comment by EcmaXp** [comment]
#42

**Comment by EcmaXp** [comment]
추가된 스노인 서버 이용해서 환경 구축하는게 좋다고 생각합니다.
@sjkoon

**Comment by sjkoon** [comment]
제가 무엇을 해야할까요

**Comment by EcmaXp** [comment]
http://www.seleniumhq.org/ 을 서버에 설치하고 Travis CI과 연동할 수 있도록 해야됩니다.

**Comment by EcmaXp** [comment]
차후 시간적 여유가 생기면 다시 열겠습니다.
