### ISSUE TITLE
게임엔님 snoin 메일 발급

### ISSUE THREAD

**Issue by item4** [Snoin/snoin.com#67]
@rpdladps

**Comment by sjkoon** [comment]
@rpdladps 아이디는 무엇으로

**Comment by rpdladps** [comment]
rpdladps@snoin.com 
이렇게 발급이 되는건가요?

**Comment by sjkoon** [comment]
그렇읍니다. 어떠세요? 다른 아이디 원하세요?

**Comment by rpdladps** [comment]
아뇨  rpdladps으로 발급해주시면 감사하겠습니다
2015. 12. 10. 10:53에 "Sangjin Cho" <notifications@github.com>님이 작성:

**Comment by sjkoon** [comment]
넹 암호는 이따..

**Comment by marnitto** [comment]
@rpdladps @sjkoon 다 되셨으면 이슈 닫아주세요~

**Comment by rpdladps** [comment]
발급 받았습니다.
