### ISSUE TITLE
최상단 이미지 변경

### ISSUE THREAD

**Issue by item4** [Snoin/snoin.com#7]
저작권은 뭐 Apache License인 것 같은데, 그래도 저희만의 이미지로 바꾸는게 좋을 것 같습니다

현재 이미지
--------------
![image](http://snoin.com/static/images/header-bg.jpg)

**Comment by sjkoon** [comment]
이건 머엉.. 의견 좀..

**Comment by item4** [comment]
@sjkoon 상진군의 연구실 책상 사진 같은거 어때요?

**Comment by item4** [comment]
아무래도 공돌공돌한 냄새가 나는 책상 사진 같은게 어떨까 하는데요 @marnitto @sjkoon

**Comment by marnitto** [comment]
음, 간단하게 쓰는 데에는 괜찮을 것 같은데 이게 사이트에 어울릴지 모르겠네요. 월요일에 샘플 사진 찍어서 업로드하겠습니다.

**Comment by sjkoon** [comment]
저도 하나 찍어 올려볼게요. 근데 제 책상이 그닥 이쁘진 않아서...

**Comment by marnitto** [comment]
책상 사진을 찍어봤는데... 이게 좀 제가 가운데 있어야 넓게 잘 쓸 수 있는 구조(파노라마??)라서 깔끔하게 보이지가 않네요.

**Comment by sjkoon** [comment]
저도 마찬가지라  제가 좋은 사진을 구해오겠습니다....

**Comment by item4** [comment]
@sjkoon @marnitto 사진 어떻게 되었나요

**Comment by sjkoon** [comment]
제 책상 너무 구려요..

**Comment by marnitto** [comment]
보여드렸었는데 별로... 그대로 가는 것도 나쁘지 않아보입니다.

**Comment by item4** [comment]
그럼 그냥 둡시다 (...)
