### ISSUE TITLE
JavaScript Uglify & Minify

### ISSUE THREAD

**Issue by item4** [Snoin/snoin.com#76]
Uglify 및 Minify를 해야할지 결정해야할 것 같습니다.

제 생각엔 Minify는 유용할지 몰라도 어차피 오픈소스이기도 하고 Uglify를 심하게 할 이유는 없지 않나 싶은데요.

**Comment by marnitto** [comment]
uglify는 찾아보니까 obfuscating(난독화)이네요. 이 부분은 말씀하신 대로 오픈 소스니까 굳이 별도로 처리할 필요가 없어보입니다.

minify…도 우리가 쓰는 javascript 코드가 그다지 길지 않아서 별 필요없어보여요.

**Comment by item4** [comment]
한분 의견만 더 듣고 이슈 닫겠습니다.

**Comment by EcmaXp** [comment]
minify

**Comment by item4** [comment]
일단 전혀 급하지 않은 이슈인 것 같아서 닫습니다. 모바일 로딩 속도가 느리다는 지적이 다시 나오면 엽시다
