### ISSUE TITLE
Services Section 내용 검토

### ISSUE THREAD

**Issue by item4** [Snoin/snoin.com#9]
제가 쓴건데 어떤지 봐주세요.

**Comment by sjkoon** [comment]
Snoin은 웹 개발 전문 개발 팀입니다. 전세계의 수많은 스타트업들이 사용하고 있는 최신 버전의 개발 도구 Python과 Flask 등을 사용하여 빠르고 안정적인 서비스를 개발합니다.

Snoin은 어떻게 하면 여러가지 환경에서 웹 서비스가 사용자에게 정보를 잘 전달할 수 있을지 생각합니다. CSS3과 JavaScript를 사용하여 다양한 기기와의 반응성을 극대화 시킵니다.

Snoin은 웹 표준을 중요시합니다. HTML5 표준을 준수하며, 문서의 시멘틱(Sementic)을 준수합니다. 검색엔진 등 타 서비스와의 연동에 보다 친화적인 서비스가 될 수 있습니다.

**Comment by item4** [comment]
다음 PR에 반영하겠습니다

**Comment by item4** [comment]
@marnitto 문장 검수 부탁드립니다.
@sjkoon 순서는 이대로면 될까요

**Comment by sjkoon** [comment]
반응형 웹
-----------
Snoin은 여러가지 환경에서 정보를 전달하는 방법에 대해 생각합니다. CSS3과 JavaScript를 사용하여 다양한 기기와의 반응성과 정보전달의 효과를 극대화 시킵니다.

웹 표준과 시멘틱
--------------------
Snoin은 웹 표준을 중요시합니다. HTML5 표준을 준수하며, 문서의 시멘틱(Sementic)을 준수합니다. 검색엔진 등 타 서비스와의 연동에 보다 친화적인 서비스를 제작합니다.

**Comment by marnitto** [comment]
기존 답변에 첨부된 대로, Services 단락에서는 고객이 우리에개 연락해야 할 만한 세일즈 포인트를 강조해야 합니다. 웹 서비스와
웹 표준이 왜 중요한지, flask를 왜 쓰는지 등이요.

저도 지금 당장에는 웹 표준을 고객사 입장에서 굳이 준수해야 할 이유를 설명하기가 어렵네요(웹알못이라). 의견 주시면 적당히 가공하는
방향으로 가겠습니다.

**Comment by item4** [comment]
@sjkoon @marnitto 
웹 서비스 개발
-----------------
전세계의 수많은 스타트업들이 사용하고 있는 최신 버전의 개발 도구 Python과 Flask 등을 사용하여 → 전 세계 수 많은 기업들이 채택했고, __탁월한 생산성이 입증된__ 최신 버전의 Python과 Flask 등을 사용하여

생산성이 중요한 것 같습니다.

반응형 웹
------------
CSS3과 JavaScript를 사용하여 다양한 기기와의 반응성과 정보전달의 효과를 극대화 시킵니다. → ~ 극대화 시켜, 사이트 방문자들로 하여금 보다 편리한 사용자 경험(UX)를 제공합니다.

반응형 웹은 UI뿐만 아니라 UX도 포함합니다.

웹 표준과 시멘틱
---------------------
검색엔진 등 타 서비스와의 연동에 특화된 서비스를 제작합니다. → 기존의 웹은 검색엔진이 내용을 추론하기 어려웠습니다. 하지만 시멘틱을 준수한 HTML5문서는 검색엔진 등 타 서비스 연동에 유리하며, 구글 등의 세계적인 기업들은 이미 시멘틱을 준수한 문서를 보다 좋은 문서로 평가하고 있으며, 소셜 연동에도 유리합니다.

웹 표준과 시멘틱은 떼놓고 이야기 할 수 없는 것 같네요

**Comment by marnitto** [comment]
## 웹 표준과 시멘틱

Snoin은 웹 표준과 시멘틱을 준수합니다. 구글, 네이버 등 검색 엔진과의 긴밀한 연동을 통해, 사용자들이 사이트에서 보여주는 정보를 더 쉽고 다양하게 접할 수 있습니다.

이전에도 답변드린 대로 이 부분은 마케팅적 관점이 필요합니다. 고객이 우리한테 사이트 개발을 맡겨서 어떤 이점이 있는지를 중심으로요.

**Comment by item4** [comment]
@marnitto 제가 쓴 내용과 적당히 섞으면 되지 않을까요?

**Comment by EcmaXp** [comment]
타 업체와 차별화를 두기 위해서 내세운 Python 및 Semantics, 그 이외의 팀원들과 관련하여 강점으로 내 세울 수 있는 부분들을 강조해야 된다고 봅니다. (이건 제 개인적인 생각이지만)

https://c9.io 에서 Awesome features 부분 처럼 만들어보고자 하는데 디자인은 좀 다르게 갈 예정입니다.
밑의 내용들은 대략적으로 적은것이라 다 엎어버릴 예정이고, 내용이나 문구, 이미지 등도 생각해 봐야 됩니다.

- [x] 보안성 강화 (Z보드 및 PHP를 사용하는 솔루션 대비)
- [ ] 빠른 속도 (PHP 대비)
- [ ] 빠른 로딩 속도 (minify, 웹폰트 최적화 등)
- [ ] 다양한 브라우저 지원
- [ ] 모바일 최적화 (앱 최적화는 생각해 봐야 됩니다.)
- [ ] 항상 대기중인 직원?
- [ ] 홈페이지를 만드는 개발자와 직접 상담 가능
- [ ] SERVICES 부분의 3가지 내용 전부 추가적으로 설명 또는 포함
- [ ] 국내 업체 강조 (?)
- [ ] HTTP/2 지원
- [ ] DDoS 방어 등. (CloudFlare 같은 곳과 연동 가능한가요?)

**Comment by item4** [comment]
* 보안성 강화: **웹 서비스 개발**에서 Python을 쓰면 좋은 장점으로써 본문 내용으로
* 빠른 속도: 실질적인 가시적 속도 차이가 있을까 싶네요.
* 빠른 로딩 속도: **컨텐츠 최적화**라는 섹션을 만드는게 어떨까요
* 다양한 브라우저 지원: **웹 표준과 시멘틱**의 본문 내용으로
* 모바일 최적화: **반응형 웹**의 본문 내용으로
* 항상 대기중인 직원: 별로 좋지 않아보입니다. 상담 가능한 사람이 24시간 대기중인건 아니니까요.
* 홈페이지를 만드는 개발자와 직접 상담 가능: 위와 동일
* SERVICES 부분의 3가지 내용 전부 추가적으로 설명 또는 포함: 당연히..
* 국내 업체 강조: 이것보다는 차라리 i18n을 미는게 어떨까 싶습니다.
* HTTP/2 지원: **컨텐츠 최적화**라는 섹션을 만드는게 어떨까요
* DDoS 방어 등: **컨텐츠 최적화**라는 섹션을 만들어서 DDoS 방어 조언을 해드린다.. 정도로 하면 어떨까요

**Comment by EcmaXp** [comment]
디도스 방어 부분은 컨텐츠 최적화 보다는 보안쪽으로 연관지어서 (파이썬과 같이) 하는게 나을 듯 합니다.
빠른 속도 부분은 최대 유저 수용 부분으로 생각해도 될 것 같고요.

**Comment by item4** [comment]
그것도 좋네요

**Comment by marnitto** [comment]
보안성 강화는 시큐어 코딩에 촛점을 맞추는 게 좋을 것 같습니다. QA 부분을 강화해서 자동화된 테스팅이나 CI쪽도 같이 얘기하면 좋고요.

한 가지 걱정되는 건, 보안 테스팅 쪽에 대해서 제가 경력사항으로 보여줄 만한 게 딱히 없네요... 개발 경력이 없다 보니까 애매합니다.

**Comment by sjkoon** [comment]
음.. 요즘 이슈인 부분들을 좀 집중적으로 어필할 필요가 있다고 봐요.

**Comment by item4** [comment]
웹 서비스 개발
--------------
국내외 수없이 많은 웹 에이전시들은 생산성도 떨어지고 보안에도 취약한 PHP로 개발을 해왔습니다. 하지만 Snoin은 웹 개발 전문 개발 팀입니다. 전 세계 수 많은 기업들이 채택했고, 탁월한 생산성이 입증된 최신 버전의 프로그래밍 언어 Python과 웹 개발 프레임워크 Flask 등을 사용하여 빠르고 안정적인 서비스를 개발합니다.

모바일 사이트와 반응형 웹
-------------------------
모바일 웹의 시대가 열렸지만 아직도 모바일 웹을 그저 "작은 웹 페이지" 정도로 여기는 회사들이 많습니다. Snoin은 어떻게 하면 여러가지 환경에서 웹 서비스가 사용자에게 정보를 잘 전달할 수 있을지 생각합니다. CSS3과 JavaScript를 사용하여 다양한 기기와의 반응성을 극대화 극대화 시켜, 사이트 방문자들로 하여금 보다 편리한 사용자 경험(UX)를 제공합니다.

웹 표준과 시멘틱
----------------
이제 웹 사이트는 전 세계에서 여러가지 방법으로 접근하는 곳이 되었습니다. 이런 세계적인 흐름 속에서 표준을 지키지 않은 사이트는 살아남을 수 없습니다. Snoin은 사이트의 웹 표준을 중요시하며, 나아가서 문서의 의미적 구조(Sementic Structure)를 중요하게 생각합니다. 기존의 웹은 검색엔진이 내용을 추론하기 어려웠습니다. 하지만 시멘틱을 준수한 HTML5문서는 검색엔진 등 타 서비스 연동에 유리하며, 구글 등의 세계적인 기업들은 이미 시멘틱을 준수한 문서를 보다 좋은 문서로 평가하고 있으며, 소셜 연동에도 유리합니다.

보안
----
과거의 웹 에이전시들은 비밀번호 등의 위험한 정보를 아예 암호화하지 않거나, md5등의 매우 취약한 방법을 사용해 잘못 다뤄왔습니다. Snoin은 기본적으로 웹 에이전시들이 많이 사용하고 있으나 보안상 좋지 않은 PHP를 버리고 Python을 사용하며, 비밀번호를 보안 전문가들이 인증한 방식으로 다루며, 국내법에서 암호화해서 취급하도록 되어있는 고객 위치 좌표값 등의 정보도 안전하게 취급할 수 있습니다.

품질 관리
---------
대부분의 웹 에이전시들은 사이트 개발을 빨리 끝내는 것이 목적일 뿐, 사이트 자체의 품질은 책임지지 않습니다. Snoin은 그렇게 개발하는 것은 안하느니만 못하다고 생각합니다. Git을 이용해서 형상 관리를 하며 GitHub을 통해 진행상황과 이슈를 관리합니다. 팀원들이 합심하여 코드 리뷰를 통해 보다 질 높고 안정적인 서비스 제공에 힘쓰고 있습니다.

컨텐츠 최적화
-------------
Snoin은 단지 웹 사이트를 개발하는 데에 그치지 않습니다. 저희와 함께하시면 분산 서비스 거부 공격(DDoS Attack)등에 대비하는 전략, 사이트의 고객들에게 보다 나은 웹 서핑 속도와 보다 안전한 웹 이용을 위한 전략을 제안해드립니다.

**Comment by marnitto** [comment]
## 보안

과거의 웹 에이전시들은 고객님의 사이트가 안전하게 운영되는지에 대한 관심이 없었습니다. 해커들은 고스란히 보이는 비밀번호, 아무렇게나 만들엉진 취약한 관리자 계정 등을 이용해 웹 사이트를 멋대로 망가뜨릴 
수 있습니다. Snoin이 제작하는 사이트는 한국인터넷진흥원 소프트웨어 개발보안 가이드를 포함한 다양한 정보보호 정책을 준수하여, 사이트를 운영하는 모두가 안전한 웹 서비스를 사용할 수 있도록 합니다.

문장을 조금 더 다듬어야 될 것 같은데... 시큐어 코딩 쪽은 CI하면서 단순히 보면 되니까 그렇게 어려울 건 없어요.

**Comment by EcmaXp** [comment]
기존의 디자인 보단 대분류 하의 소분류 아이템들로 간단간단하게 구성하는 건 어떻게 생각하시나요.

**Comment by item4** [comment]
@EcmaXp 저도 그 생각은 해봤는데, 한번 그림판으로라도 간단하게 예시를 그려주세요.

**Comment by item4** [comment]
@marnitto fork

보안
----
과거의 웹 에이전시들은 고객님의 사이트가 안전하게 운영되는지에 대한 관심이 없었습니다. 해커들은 고스란히 보이는 암호화 되지 않거나 잘못 관리된 비밀번호, 아무렇게나 만들어진 취약한 관리자 계정 시스템 등을 이용해 웹 사이트를 멋대로 망가뜨리고 정보를 유출시킬 수 있습니다. Snoin이 제작하는 사이트는 한국인터넷진흥원 소프트웨어 개발보안 가이드를 포함한 다양한 정보보호 정책을 준수하여, 사이트를 운영하는 모두가 안전한 웹 서비스를 사용할 수 있도록 합니다.

**Comment by marnitto** [comment]
그대로 잘 반영됐네요. 바뀐 게 없어보이지만..

fork는 제가 PR로 따로 올리는 게 좋다는 말씀이신가요?

**Comment by item4** [comment]
@marnitto 단어 몇개 더 넣었습니다. *암호화 되지 않거나 잘못 관리된* 비밀번호 라던가 관리자 계정 *시스템* 이라던가..

**Comment by item4** [comment]
PR은 제가 올릴게요

**Comment by EcmaXp** [comment]
![default](https://cloud.githubusercontent.com/assets/13285311/11121155/9d2c1c12-8997-11e5-9dcf-1048a8e104a5.png)
3분작입니다 [...

**Comment by EcmaXp** [comment]
@marnitto 사이트를 운영하는 -> 사이트를 이용하는 (또는 다른 키워드 사용하여서 관리자 뿐만이 아닌 사용자 부분도 강조)?

**Comment by marnitto** [comment]
맞아요. 고객(사이트 제작 의뢰자)뿐만 아니라 고객(사이트 이용자)에게도 포괄적으로 도움이 된다는 걸 말하고 싶었어요.

**Comment by item4** [comment]
과거의 웹 에이전시들은 고객님의 사이트가 안전하게 운영되는지에 대한 관심이 없었습니다. 해커들은 고스란히 보이는 암호화 되지 않거나 잘못 관리된 비밀번호, 아무렇게나 만들어진 취약한 관리자 계정 시스템 등을 이용해 웹 사이트를 멋대로 망가뜨리고 정보를 유출시킬 수 있습니다. Snoin이 제작하는 사이트는 한국인터넷진흥원 소프트웨어 개발보안 가이드를 포함한 다양한 정보보호 정책을 준수하여, 사이트를 이용하는 모두가 안전한 웹 서비스를 사용할 수 있도록 합니다.

**Comment by sjkoon** [comment]
너무 교과서적인 표현보다는 그냥 포말하게 안전하다는 정도로 설명해도 용이할거같아요 제 생각엔

**Comment by marnitto** [comment]
Snoin이 제작하는 사이트는 한국인터넷진흥원 소프트웨어 개발보안 가이드를 포함한 다양한 정보보호 정책을 준수하여, 사이트를 이용하는
모두가 안전한 웹 서비스를 사용할 수 있도록 합니다.

다른 문단에 비해 분량이 많은 것 같아서 지워봤습니다

**Comment by item4** [comment]
다른 문단들도 이미 길지 않나 싶습니다. 다 같이 길던지, 다 같이 짧던지 해야할 것 같습니다.

**Comment by EcmaXp** [comment]
짧으면서 소 아이템 추가 설명이 어떤가요

**Comment by item4** [comment]
@EcmaXp 그런 버전을 이미지 만들어오신다고 하셨던걸로 기억해서 기다리고 있습니다...

**Comment by sjkoon** [comment]
웹 서비스 개발
--------------
Snoin은 전 세계 수 많은 기업들이 채택하고, 탁월한 생산성이 입증된 최신 버전의 프로그래밍 언어와 웹 개발 프레임워크 등을 사용하여 안정적인 서비스를 빠르게 개발합니다.

모바일 사이트와 반응형 웹
-------------------------
모바일 웹의 시대가 열렸지만 아직도 모바일 웹을 그저 "작은 웹 페이지" 정도로 여기는 회사들이 많습니다. Snoin은 다양한 기기와의 반응성을 극대화 극대화 시켜, 사이트 방문자들로 하여금 보다 편리한 사용자 경험(UX)를 제공합니다.

보안
----
과거의 웹 에이전시들은 비밀번호 등의 위험한 정보를 아예 암호화하지 않거나, 취약한 방법을 사용해 문제가 발생했습니다. Snoin은 기본적으로 비밀번호를 보안 전문가들이 인증한 방식으로 다루며, 국내법에서 암호화해서 취급하도록 되어있는 정보들 또한 안전하게 취급할 수 있습니다.

품질 관리
---------
대부분의 웹 에이전시들은 사이트 개발을 빨리 끝내는 것이 목적일 뿐, 사이트 자체의 품질은 책임지지 않습니다. Snoin은 버전관리 시스템을 이용해서 어플리케이션을 관리하며, 질 높고 안정적인 서비스 제공에 힘쓰고 있습니다.

컨텐츠 최적화
-------------
Snoin은 단지 웹 사이트를 개발하는 데에 그치지 않습니다. 저희는 분산 서비스 거부 공격(DDoS Attack)등에 대비하는 전략, 사이트의 고객들에게 보다 나은 웹 서핑 속도와 보다 안전한 웹 이용을 위한 전략을 제안해드립니다.

**Comment by sjkoon** [comment]
너무 기술적인 내용은 고객들이 보기에 부담스럽거나 이해하기 어렵습니다.

최대한 배제하여 내용을 줄여봤습니다.

**Comment by item4** [comment]
저는 좋아보이는데, PR 만들어서 올리도록 하겠습니다. (PR 머지 될때까지 닫지 말아주세요)

**Comment by sjkoon** [comment]
수정안에 대해 좀 더 많은 의견 바랍니다 @Snoin/owners
