### ISSUE TITLE
고객의 실질적 Needs를 반영한 Service section

### ISSUE THREAD

**Issue by item4** [Snoin/snoin.com#90]
IRC에서 논의해본 결과 고객의 실질적 Needs는 크게 2가지로 나뉜다는 것을 알게 되었고, 그것에 따라 개발 언어가 PHP와 Python으로 나뉘게 될 것이란 것도 합의되었습니다.

이 부분을 웹사이트에 명시하는 것이 좋다고 생각합니다.

저는 이 부분을 자가진단 형태로 만들어서, 선택한 결과를 상담 폼에 자동으로 포함하도록 하는 쪽이 어떨까 생각합니다.

## 원하시는 사이트의 일일 방문자는 어느 정도 될 것 같으신가요?
- 그리 많지 않다
- 일일 1,000명 이상 방문한다
- 일일 1,000,000명 이상 방문한다

## 예상하는 방문자는 주로 어느 계층인가요?
- 계산용 POS기, 공공기관등의 Windows XP 환경
- PC방, 가정집 등의 Windows 7 이상의 환경
- 스마트폰
- Mac OSX, Linux 등의 특수 환경
- 잘 모른다

## 사이트가 모바일 환경(스마트폰)에서도 잘 보여야 하나요?
- 네
- 아니요

## 어떤 기능들을 필요로 하시나요? (복수 선택 가능)
- 단순한 소개 페이지
- 게시판
- 회원 시스템
- 소셜 연동
- 블로그
- 쇼핑몰
- 동영상 서비스
- 다국어 지원
- 기타

## 개발비용은 어느정도로 생각하고 계신가요? 적절한 방법을 제시해드립니다.
- 300,000원 미만
- 1,000,000원 미만
- 1,000,000원 이상
- 생각해본 적 없다

## 디자인은 어떻게 하실 생각이신가요?
- 의뢰한 곳에 디자이너 선임을 일임한다
- 자체 디자이너를 구했거나 구할 생각이다
- 특수한 사이트여서 디자인이 전혀 필요 없다

## 유지보수 비용은 어느정도로 생각하고 계신가요?
- 연 50,000원 이하
- 연 200,000원 이하
- 규모 변화에 따라 변하도록

## 유지보수는 어떻게 하실 생각이신가요?
- 개발한 곳에서 계속 해주었으면 한다
- 자체적으로 하거나 다른 곳에 의뢰할 예정이다

**Comment by item4** [comment]
@Snoin/owners 모두 확인해서 문항 검수 부탁드립니다. 이견 없으면 이번 토~일 중으로 PR 올리겠습니다.

**Comment by marnitto** [comment]
개발 비용에 관한 부분은 다른 항목과 별개로 보여줘야 될 것 같습니다. 지금 시트대로면 모바일에 다국어 지원에 ie6부터 죄다 지원되는
반응형 웹사이트를 30만원에 유지보수비 없이 만들어달라는 요구(...)도 일단 받아주겠다는 듯이 보여요.

우리 플랜의 대략적인 견적을 알고 싶은 거라면, 적당한 샘플을 보여주면서 여기엔 뭐뭐가 들어가있고 적정견적은 어느 정도 된다는 식으로
보여주는 게 좋지 않을까요? 유료 플랜에서 가격 다음에 이것저것 기능 보여주는 것처럼요.

**Comment by item4** [comment]
@marnitto 가격을 웹상에서 임시 견적으로라도 정해주면 실제 상담에서 왜 그거보냐 비싸냐고 싸움이 날 게 뻔합니다 (...)

아무래도 이 부분은 데모 사이트를 몇개 만들고, 데모 사이트의 예상 가격을 보여주는 방식으로 가야할 것 같습니다

**Comment by marnitto** [comment]
네, 말씀하신 대로가 좋겠네요. 데모는 소스 공개 안 하죠?
2016. 2. 12. 오전 10:33에 "item4" <notifications@github.com>님이 작성:

**Comment by item4** [comment]
데모는 디자인+퍼블리싱만 하는게 좋겠습니다. 실제 동작할 필요는 없는 것 같아요

**Comment by sjkoon** [comment]
음.. 생각해보니 위와 같은 문제가 있네요... 뭐 30에 모바일같은걸 요구하면 다른부분을 낮춰서 맞춰주는것도 나쁘지 않지 않을까요

**Comment by item4** [comment]
@sjkoon 불가능한 의뢰는 상담 단계에서 확실하게 설명을 해줘야한다고 생각합니다. 위에 놓은건 어디까지나 예상 가격이고 실제 가격이 될 순 없죠.

**Comment by sjkoon** [comment]
네 불가능한건 불가능하다 해야죠 당연히.

**Comment by rpdladps** [comment]
노코멘트
