### ISSUE TITLE
JavaScript Coding Convention

### ISSUE THREAD

**Issue by item4** [Snoin/snoin.com#91]
지금까진 그냥 막 썼는데(...) 지금까진 저 혼자 JS 코딩을 했으니 탈이 없었지만 여러 사람 손이 가면 아무래도 문제가 생길 것 같습니다.

몇가지 훑어봤는데 제가 제안하고 싶은 것은 [airbnb 컨벤션입니다.](https://github.com/airbnb/javascript)
회사 이름만 봐서는 비행기라도 타야할 것 같은데 그런거 없고 매우 잘 정리된 컨벤션입니다.

다만 좀 분량이 많고, ES6를 모르면 난해할 수 있다는게 단점이네요.

저는 이걸 `CONTRIBUTING.rst`에 넣고 Snoin 표준으로 삼고, 모든 코드에 [eslint](http://eslint.org)를 사용해서 문법 준수 여부를 검사했으면 합니다.

**Comment by item4** [comment]
@Snoin/owners 본 레포 외에도 snoin에서 진행하는 외주 등에도 적용해야하는 관계로 이번 일요일까지는 결정했으면 합니다.

**Comment by sjkoon** [comment]
airbnb 컨벤션 나쁘진 않은거같은데 역시 배우는건 힘드네요
